name: Future
favicon: null
layout_spectrum: 0.28262
typography_spectrum: 0.71479
title: Futurist Explores Today and Tomorrow
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#dfdfdf'
    - '#a5a5a5'
    - '#1a1a1a'
    - '#777777'
    - '#3b3b3b'
  brandStrength: 0.5625
  lightness: 1
  saturation: 1
  rhythmicContrast: 0.25
purpose: []
