name: Future
favicon: null
layout_spectrum: 0.28262
typography_spectrum: 0.15933901676908135
title: Futurist Explores Today and Tomorrow
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.5625
  lightness: 1
  saturation: 1
  rhythmicContrast: 0.25
purpose: []
